name: Test Docs

on:
  pull_request:
  push:
    branches: [ main ]

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - name: Install deps
        run: |
          python -m pip install -U pip
          pip install -e .  # install semantiva for imports
          pip install sphinx sphinx-autobuild sphinx-autodoc-typehints sphinxcontrib-mermaid furo myst-parser
      - name: YAML import sanity
        run: python docs/tools/verify_yaml_refs.py
      - name: Sphinx doctest
        run: make -C docs doctest
      - name: Sphinx html
        run: make -C docs html
      - name: Sphinx linkcheck
        run: make -C docs linkcheck
